title: Himadri Chowdhury
position: Engineering Manager
affiliation: MGH Group
email: himadrichowdhury172 (at) gmail (dot) com
keywords: minimal academic
github_link: https://github.com/himadri001
linkedin: https://linkedin.com/in/himadri-chowdhury-549820160
cv_link: ./assets/pdf/Himadri_Chy_Resume.pdf
avatar: ./assets/img/mypic.JPG
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
